@rem - Encoding:gb2312; Mode:Batch; Language:zh-CN; LineEndings:CRLF -
:: START OF TRANSLATION
set "str_title=视频下载器 一键配置"
set "str_titleExpanded=========  %str_title%  ========"
:: Menu Options
set "str_portable=绿色配置"
set "str_quickstart=快速配置"
set "str_withpip=完整配置"
set "str_opt1=初始配置"
set "str_opt11=绿色便携版，可以任意移动整体文件夹。默认"
set "str_opt12=快速体验，适合临时使用"
set "str_opt13=通过 pip 稳定更新，适合长期使用"
set "str_opt2=配置 FFmpeg"
set "str_opt3=更新所有视频下载器"
set "str_opt4=重新创建启动脚本"
set "str_opt5=更新此脚本 (访问 GitHub)"
set "str_opt6=高级设置"
set "str_please-choose=请输入选项的序号并按回车: "
set "str_please-choose-from=请从 11 , 12 , 13 中选择 "
set "str_please-input-valid-num=请输入有效的数字。"
set "str_please-set-DeployMode=未找到 "deploy.log" ，无法判断配置模式，请手动选择 [11, 12, 13]: "
:: Notification
set "str_bat-is-latest=此脚本已是最新。"
set "str_bat-can-update-to=此脚本可更新至"
set "str_deploy-ok=配置已完成。"
set "str_upgrade-ok=更新已完成。"
set "str_is-latestVersion=已是最新发行版"
set "str_please-wait=请耐心等待下载完成"
set "str_please-init=请先执行初始配置。"
set "str_please-re-init=请删除 "usr" 文件夹后再执行此选项。"
set "str_please-check-connection=无法访问 GitHub ，请检查网络连接。"
set "str_fileLost=文件丢失，请重新下载或解压此脚本的所有文件。"
:: :: use ^) instead of ), since %str_open-webpage% will be used in "if ( ) esle( )"
set "str_open-webpage1=按任意键以查看 GitHub 主页 (打开浏览器访问 GitHub^)"
set "str_open-webpage2=按任意键以获取更新 (打开浏览器访问 GitHub^)"
:: Procedure
set "str_downloading=正在下载"
set "str_unzipping=正在解压"
set "str_upgrading=正在更新"
set "str_updating=正在更新"
set "str_checking-connection=正在检查网络连接 (如果长时间无响应，请确认网络是否正常)"
set "str_checking-update=正在检查更新"
set "str_already-deploy=已配置。"
set "str_already-upgraded=已更新。"
:: Guides of download batch
set "str_dl-guide1=下载视频的命令为："
set "str_dl-guide2=you-get/youtube-dl/annie + 视频网址"
set "str_dl-guide3=例如："
set "str_dl-guide4=默认下载最高清晰度。下载文件默认保存在 Download 目录。"
set "str_dl-guide5=如果你想选择清晰度、更改默认路径，或想了解三种工具的其他用法，请百度或参考官方说明："
set "str_dl-guide_wiki=中文说明"
:: Contents of download batch
set "str_dl-bat=下载视频"
set "str_dl-bat-created=已创建启动脚本 "%str_dl-bat%.bat" 。"
set "str_dl-bat-moved=未找到 "usr" 文件夹！请将此脚本移动到与 "Deploy.bat" 同一目录，或通过其重新创建启动脚本。"
:: Advanced Settings
set "str_opt6-Expanded======= 高级设置 ======"
set "str_opt6_opt0=返回主菜单"
set "str_opt6_opt1=选择语言 (Select Language)"
set "str_opt6_opt2=选择下载地区"
set "str_opt6_opt3=(显示/隐藏) 代理参数的命令示例"
set "str_opt6_opt4=(禁用/启用) FFmpeg"
set "str_opt6_opt5=为 'wget' 设置参数"
set "str_please-select-language=[11] English ; [12] 简体中文"
set "str_language-set-to=语言已设置为："
set "str_please-select-region=[21] 官方源 (origin) ; [22] 国内镜像源 (cn)"
set "str_current-region=当前下载地区为："
set "str_region-set-to=下载地区已设置为："
set "str_please-rerun=请重新运行此脚本以使设置生效。"
set "str_proxyHint-enabled=代理参数的命令示例：显示"
set "str_proxyHint-disabled=代理参数的命令示例：隐藏"
set "str_proxyHint-setting=代理设置："
set "str_ffmpeg-enabled=FFmpeg 已启用。"
set "str_ffmpeg-disabled=FFmpeg 已禁用。"
set "str_wget-option-is=当前 'wget' 所使用的参数为："
set "str_please-rerun-dlbat=请重新运行 "%str_dl-bat%.bat" 以使设置生效。"
set "str_please-edit-wget-opt_1=请自行编辑 "res\wget.opt" 以修改默认参数。"
set "str_please-edit-wget-opt_2=修改后请重新执行此选项以确认设置无误。"
set "str_please-edit-wget-opt_3=若需重新生成默认的 "wget.opt" ，请输入：50"
set "str_reset-wget-opt-ok=已重新生成 "wget.opt" 。"
:: END OF TRANSLATION
:: Select mirror for sources.txt
set "_Region_=cn"