@rem - Encoding:utf-8; Mode:Batch; Language:en; LineEndings:CRLF -
:: START OF TRANSLATION
set "str_title=Video Downloader One-click Deploy"
set "str_titleExpanded==  %str_title%  ="
:: Menu Options
set "str_portable=Portable Deploy "
set "str_quickstart=Quickstart      "
set "str_withpip=Full Deploy     "
set "str_opt1=Initial Deployment"
set "str_opt11=Portable, move the folder at will. DEFAULT"
set "str_opt12=Quick experience, suitable for temporary use"
set "str_opt13=Keep upgrade through pip, suitable for long-term use"
set "str_opt2=Deploy FFmpeg"
set "str_opt3=Upgrade all the Video Downloaders"
set "str_opt4=Re-create the start batch"
set "str_opt5=Update this batch (Visit GitHub)"
set "str_opt6=Advanced Settings"
set "str_please-choose=Please input the index number of option and press ENTER:"
set "str_please-choose-from=Please choose from 11 , 12 , 13 ."
set "str_please-input-valid-num=Please input a valid number."
set "str_please-set-DeployMode=NOT founded "deploy.log" . Unable to judge the Deploy Mode. Please choose manually [11, 12, 13]: "
:: Notification
set "str_bat-is-latest=This batch is the latest version."
set "str_bat-can-update-to=This batch can be updated to"
set "str_deploy-ok=Deployment done."
set "str_upgrade-ok=Upgrade done."
set "str_is-latestVersion=is the latest Release version"
set "str_please-wait=Please be patient while waiting for the download"
set "str_please-init=Please perform the Initial Deployment first."
set "str_please-re-init=The Initial Deployment has been done. Please delete the "usr" folder before performing this option."
set "str_please-check-connection=Unable to access GitHub, please check your network connection."
set "str_fileLost=File Lost. Please re-download or re-unzip all the files of this batch."
:: :: use ^) instead of ), since %str_open-webpage% will be used in "if ( ) esle( )"
set "str_open-webpage1=Press any key to visit the GitHub page (Start your browser to visit GitHub^)"
set "str_open-webpage2=Press any key to get updated (Start your browser to visit GitHub^)"
set "str_exit=Press any key to exit..."
:: Procedure
set "str_downloading=Downloading"
set "str_unzipping=Unzipping"
set "str_upgrading=Upgrading"
set "str_updating=Updating"
set "str_checking-connection=Checking network connection"
set "str_checking-update=Checking update"
set "str_already-deploy=already deployed."
set "str_already-upgrade=already upgraded."
set "str_already-exist=already exists."
:: Guides of download batch
set "str_dl-guide1=The command to download a video is:"
set "str_dl-guide2=you-get/youtube-dl/annie + [video URL]"
set "str_dl-guide3=For example:"
set "str_dl-guide4=By default, you will get the video of highest quality. And the files downloaded will be saved in "Download"."
set "str_dl-guide5=If you want to choose the quality of video, change the directory saved in, or learn more usage of these tools, please Google it or refer to the Official Instructions:"
set "str_dl-guide_wiki="
:: Contents of download batch
set "str_dl-bat=Download_Video"
set "str_dl-bat-created=The start batch "%str_dl-bat%.bat" has been created."
set "str_dl-bat-moved=The "usr" folder was not found. Please move this batch to the same directory as "Deploy.bat" or re-create the start batch through it."
:: Advanced Settings
set "str_opt6-Expanded== Advanced  Settings ="
set "str_opt6_opt0=Return to the Main Menu"
set "str_opt6_opt1=Select Language"
set "str_opt6_opt2=Select Download Region"
set "str_opt6_opt3=(Display/Hide) the examples of proxy options"
set "str_opt6_opt4=(Disable/Enable) FFmpeg"
set "str_opt6_opt5=Set options for 'wget'"
set "str_opt6_opt6=(Disable/Enable) Network connection test while upgrading"
set "str_please-select-language=[11] English ; [12] Simplified Chinese"
set "str_language-set-to=Language has been set to:"
set "str_please-select-region=[21] Origin website (origin) ; [22] CN mirror (cn)"
set "str_current-region=The current Download Region is:"
set "str_region-set-to=Download Region been set to:"
set "str_please-rerun=Please re-run this batch to make the settings take effect."
set "str_proxyHint-enabled=Examples of proxy options: Displayed"
set "str_proxyHint-disabled=Examples of proxy options: Hidden ^(DEFAULT^)"
set "str_proxyHint-setting=Proxy settings:"
set "str_ffmpeg-enabled=FFmpeg: enabled ^(DEFAULT^)"
set "str_ffmpeg-disabled=FFmpeg: disabled"
set "str_wget-option-is=The current options of 'wget' are:"
set "str_please-rerun-dlbat=Please re-run the "%str_dl-bat%.bat" to make the settings take effect."
set "str_please-edit-wget-opt_1=Please edit the "res\wget.opt" manually to change the default options."
set "str_please-edit-wget-opt_2=Please re-perform this step here to confirm the modification."
set "str_please-edit-wget-opt_3=To reset the default "wget.opt", please enter: 50"
set "str_reset-wget-opt-ok=The "wget.opt" has been reset."
set "str_netTest-enabled=Network connection test while upgrading: enabled ^(DEFAULT^)"
set "str_netTest-disabled=Network connection test while upgrading: disabled"
:: END OF TRANSLATION
:: Select mirror for sources.txt
set "_Region_=origin"